name: verzel_app
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=2.19.6 <3.0.0'

dependencies:
  another_flushbar: ^1.12.29
  auto_size_text: ^3.0.0
  cryptography: ^2.5.0

  dartz: ^0.10.1
  encrypt: ^5.0.1
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  flutter_image_compress: ^2.0.4
  flutter_localizations:
    sdk: flutter
  flutter_svg: ^2.0.7
  google_fonts: ^4.0.4
  hive: ^2.2.3
  html: ^0.15.4
  http: ^0.13.5
  image_picker: ^1.0.4
  intl: ^0.18.0
  lottie: ^2.6.0
  package_info: ^2.0.2
  path_provider: ^2.0.14
  provider: ^6.0.5
  responsive_sizer: ^3.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true  
  
  assets:
    - lib/app/common/assets/
    - lib/app/common/assets/lottie/
    - lib/app/common/assets/png/
